name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform Format & Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    
    - name: Terraform Format Check
      run: tofu fmt -check -recursive
      working-directory: tofu
    
    - name: Terraform Init
      run: tofu init
      working-directory: tofu
    
    - name: Terraform Validate
      run: tofu validate
      working-directory: tofu
    
    - name: TFLint Setup
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
    
    - name: TFLint Init
      run: tflint --init
      working-directory: tofu
    
    - name: TFLint
      run: tflint
      working-directory: tofu

  python:
    name: Python Format & Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e .
        uv pip install ruff pytest
    
    - name: Ruff Format Check
      run: uv run ruff format --check .
    
    - name: Ruff Lint
      run: uv run ruff check .
    
    - name: Run Tests
      run: uv run python -m pytest spark_jobs/tests/ -v